### ISSUE TITLE
Remove domain from links

### ISSUE THREAD

**Issue by RealOrangeOne** [PeterJCLaw/code-submitter#31]
As fixed in https://github.com/srobo/ansible/pull/37, we discovered an issue where the URLs were rendered with a domain, which caused issues when running behind a reverse proxy which wasn't passing the `Host` header through correctly.

In reality, we should stop rendering domains with the URLs, instead using site-absolute URLs (`/download` etc). 

[`url_for`](https://www.starlette.io/routing/#reverse-url-lookups) always returns a URL including the domain, which is rather annoying. There's a `url_path_for`, but this seems to not be accessible in the request context

**Comment by PeterJCLaw** [comment]
Does `url_path_for` correctly handle the proxied application prefix? For example: if we proxied the code submitter at `/spam/` or `/code-submitter/spam/` would it correctly handle that?
I have a vague recollection that this may have been why it uses `url_for` rather than `url_path_for`. Needs testing I expect.

**Comment by PeterJCLaw** [comment]
Ok, testing those two alternatives by running as `./script/uvicorn --root-path /code-submitter`:
```
app.url_path_for('homepage')='/'
request.url_for('homepage')='http://localhost:8000/code-submitter/'
```
I think there are essentially two modes that you can use here:
- one where the app is purely self-relative
- one where the app is aware of its environment

In the first case I think the expectation would also be that the proxy would inject the prefixes (here `/code-submitter`) in front of any links included in the responses. The few times I've needed to do that it's not felt at all like the right thing for the proxy to be doing (string munging in nginx via its config isn't pretty), so I'm fairly sure we want the other style.

This likely means that the solution here is to fix the way that the hosting server is operating under its proxy.

**Comment by PeterJCLaw** [comment]
Closing as I believe that this is an issue with the proxy, not the application.
